# -*- coding: utf-8 -*-
"""Counting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-xGW3Zko9Z6vm06bOvnFmBmyroXd7yA
"""

score = input()
scores = score.split(' ')
count = 0
for i in scores:
  if int(i) < 60:
    count += 1
print(count)